-- ============================================================
-- 012_record_visit_rpc.sql
-- Atomic RPC: "Record Visit" (session + optional payment)
--
-- Wraps ALL writes for the combined "Record Visit + Payment"
-- workflow in a single Postgres transaction:
--   1. Validate package status, branch, sessions, overpayment
--   2. Create sale + sale_item + payment (if payment_amount > 0)
--   3. Insert package_payment (trigger syncs total_paid)
--   4. Consume session (trigger syncs sessions_used)
--   5. Deduct BOM consumables + write inventory_logs
--   6. Record doctor commission
--   7. Auto-complete package if fully consumed
--
-- Any failure at any step → full transaction rollback.
-- No partial state is ever committed.
-- ============================================================

CREATE OR REPLACE FUNCTION record_package_visit(
  p_package_id       UUID,
  p_branch_id        UUID,
  p_performed_by     UUID,
  p_doctor_id        UUID       DEFAULT NULL,
  p_sessions_count   INT        DEFAULT 1,
  p_notes            TEXT       DEFAULT NULL,
  -- Payment parameters (all optional; omit or set amount=0 for session-only)
  p_payment_amount   NUMERIC(10,2)  DEFAULT 0,
  p_payment_method   payment_method DEFAULT 'cash',
  p_reference_number VARCHAR(100)   DEFAULT NULL,
  p_receipt_number   TEXT       DEFAULT NULL,   -- pre-generated by caller
  p_customer_id      UUID       DEFAULT NULL,
  p_service_name     TEXT       DEFAULT NULL    -- for sale_items.name
) RETURNS JSONB AS $$
DECLARE
  v_pkg              RECORD;
  v_service_id       UUID;
  v_sessions_remaining INT;
  v_remaining_balance NUMERIC(10,2);
  -- BOM
  v_bom              RECORD;
  v_inv              RECORD;
  v_new_qty          INT;
  -- Session
  v_session_id       UUID;
  -- Payment
  v_sale_id          UUID;
  v_sale_item_id     UUID;
  v_payment_id       UUID;
  v_pkg_payment_id   UUID;
  -- Commission
  v_doc              RECORD;
  v_gross_amount     NUMERIC(10,2);
  v_comm_amount      NUMERIC(10,2);
  v_comm_rate        NUMERIC(5,4);
  v_auto_completed   BOOLEAN := FALSE;
BEGIN
  -- ══════════════════════════════════════════════════════════
  -- 1. LOCK + VALIDATE PACKAGE (before any mutation)
  -- ══════════════════════════════════════════════════════════

  SELECT * INTO v_pkg
    FROM patient_packages
    WHERE id = p_package_id
    FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Package not found'
      USING ERRCODE = 'P0002';
  END IF;

  IF v_pkg.status != 'active' THEN
    RAISE EXCEPTION 'Package is % — cannot consume sessions', v_pkg.status;
  END IF;

  IF v_pkg.branch_id != p_branch_id THEN
    RAISE EXCEPTION 'Branch mismatch'
      USING ERRCODE = '42501';
  END IF;

  v_service_id := v_pkg.service_id;
  v_sessions_remaining := v_pkg.total_sessions - v_pkg.sessions_used;

  IF p_sessions_count > v_sessions_remaining THEN
    RAISE EXCEPTION 'Insufficient sessions. Remaining: %, Requested: %',
      v_sessions_remaining, p_sessions_count;
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- 2. VALIDATE PAYMENT (before any mutation)
  -- ══════════════════════════════════════════════════════════

  IF p_payment_amount > 0 THEN
    v_remaining_balance := v_pkg.total_price - v_pkg.total_paid;

    IF p_payment_amount > v_remaining_balance + 0.01 THEN
      RAISE EXCEPTION 'Payment exceeds remaining balance. Balance: %, Payment: %',
        v_remaining_balance, p_payment_amount;
    END IF;

    IF p_receipt_number IS NULL OR TRIM(p_receipt_number) = '' THEN
      RAISE EXCEPTION 'receipt_number is required when payment_amount > 0';
    END IF;
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- 3. PRE-VALIDATE BOM STOCK (before any mutation)
  -- ══════════════════════════════════════════════════════════

  FOR v_bom IN
    SELECT sc.product_id,
           sc.quantity * p_sessions_count AS needed,
           p.name AS product_name
    FROM service_consumables sc
    JOIN products p ON p.id = sc.product_id
    WHERE sc.service_id = v_service_id
  LOOP
    SELECT * INTO v_inv
      FROM inventory
      WHERE product_id = v_bom.product_id
        AND branch_id  = p_branch_id
      FOR UPDATE;

    IF NOT FOUND OR v_inv.quantity < v_bom.needed THEN
      RAISE EXCEPTION 'Insufficient stock for "%": need %, have %',
        v_bom.product_name, v_bom.needed, COALESCE(v_inv.quantity, 0);
    END IF;
  END LOOP;

  -- ══════════════════════════════════════════════════════════
  -- ALL VALIDATIONS PASSED — begin mutations
  -- ══════════════════════════════════════════════════════════

  -- ══════════════════════════════════════════════════════════
  -- 4. PAYMENT WRITES (if payment_amount > 0)
  --    Done BEFORE session consumption so if these fail,
  --    no session is consumed.
  -- ══════════════════════════════════════════════════════════

  IF p_payment_amount > 0 THEN
    -- 4a. Create sale record
    INSERT INTO sales (
      receipt_number, branch_id, user_id, customer_id,
      subtotal, discount, tax, total,
      status, payment_type, notes
    ) VALUES (
      p_receipt_number, p_branch_id, p_performed_by, p_customer_id,
      p_payment_amount, 0, 0, p_payment_amount,
      'completed', 'installment',
      'Installment payment — ' || COALESCE(p_service_name, 'Package Service')
    ) RETURNING id INTO v_sale_id;

    -- 4b. Create sale_item
    INSERT INTO sale_items (
      sale_id, item_type, service_id, name,
      quantity, unit_price, total_price
    ) VALUES (
      v_sale_id, 'service', v_service_id,
      COALESCE(p_service_name, 'Package Service') || ' — Installment Payment',
      1, p_payment_amount, p_payment_amount
    ) RETURNING id INTO v_sale_item_id;

    -- 4c. Create payment
    INSERT INTO payments (
      sale_id, method, amount, reference_number
    ) VALUES (
      v_sale_id, p_payment_method, p_payment_amount, p_reference_number
    ) RETURNING id INTO v_payment_id;

    -- 4d. Create package_payment (trigger syncs total_paid automatically)
    INSERT INTO package_payments (
      package_id, branch_id, received_by,
      amount, method, reference_number, notes
    ) VALUES (
      p_package_id, p_branch_id, p_performed_by,
      p_payment_amount, p_payment_method, p_reference_number,
      'Installment payment — Receipt ' || p_receipt_number
    ) RETURNING id INTO v_pkg_payment_id;
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- 5. CONSUME SESSION (trigger syncs sessions_used)
  -- ══════════════════════════════════════════════════════════

  INSERT INTO package_sessions (
    package_id, branch_id, performed_by,
    doctor_id, sessions_count, notes
  ) VALUES (
    p_package_id, p_branch_id, p_performed_by,
    p_doctor_id, p_sessions_count, p_notes
  ) RETURNING id INTO v_session_id;

  -- ══════════════════════════════════════════════════════════
  -- 6. DEDUCT BOM + WRITE INVENTORY LOGS
  -- ══════════════════════════════════════════════════════════

  FOR v_bom IN
    SELECT sc.product_id,
           sc.quantity * p_sessions_count AS needed
    FROM service_consumables sc
    WHERE sc.service_id = v_service_id
  LOOP
    SELECT * INTO v_inv
      FROM inventory
      WHERE product_id = v_bom.product_id
        AND branch_id  = p_branch_id
      FOR UPDATE;

    v_new_qty := v_inv.quantity - v_bom.needed;
    UPDATE inventory SET quantity = v_new_qty WHERE id = v_inv.id;

    INSERT INTO inventory_logs (
      inventory_id, product_id, branch_id, performed_by,
      source, quantity_delta, quantity_before, quantity_after,
      package_session_id, notes
    ) VALUES (
      v_inv.id, v_bom.product_id, p_branch_id, p_performed_by,
      'service_bom', -v_bom.needed, v_inv.quantity, v_new_qty,
      v_session_id,
      'BOM deduction for session on package ' || p_package_id
    );
  END LOOP;

  -- ══════════════════════════════════════════════════════════
  -- 7. DOCTOR COMMISSION
  -- ══════════════════════════════════════════════════════════

  IF p_doctor_id IS NOT NULL THEN
    SELECT * INTO v_doc FROM doctors WHERE id = p_doctor_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Doctor % not found in doctors table', p_doctor_id;
    END IF;
    IF NOT v_doc.is_active THEN
      RAISE EXCEPTION 'Doctor % is inactive', p_doctor_id;
    END IF;

    v_gross_amount := (v_pkg.total_price::NUMERIC / v_pkg.total_sessions) * p_sessions_count;
    v_comm_rate := NULL;
    v_comm_amount := 0;

    IF v_doc.default_commission_type = 'fixed' THEN
      v_comm_amount := COALESCE(v_doc.default_commission_value, 0);
    ELSE
      v_comm_rate := COALESCE(v_doc.default_commission_value, 0);
      v_comm_amount := v_gross_amount * v_comm_rate;
    END IF;

    IF v_comm_amount > 0 THEN
      INSERT INTO doctor_commissions (
        branch_id, doctor_id, package_session_id,
        gross_amount, commission_rate, commission_amount
      ) VALUES (
        p_branch_id, p_doctor_id, v_session_id,
        v_gross_amount, v_comm_rate, ROUND(v_comm_amount, 2)
      );
    END IF;
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- 8. AUTO-COMPLETE IF FULLY CONSUMED
  -- ══════════════════════════════════════════════════════════

  v_auto_completed := (v_pkg.sessions_used + p_sessions_count) >= v_pkg.total_sessions;

  IF v_auto_completed THEN
    UPDATE patient_packages SET status = 'completed'
      WHERE id = p_package_id;
  END IF;

  -- ══════════════════════════════════════════════════════════
  -- RETURN
  -- ══════════════════════════════════════════════════════════

  RETURN jsonb_build_object(
    'session_id',          v_session_id,
    'sessions_remaining',  v_sessions_remaining - p_sessions_count,
    'auto_completed',      v_auto_completed,
    'sale_id',             v_sale_id,
    'receipt_number',      p_receipt_number,
    'package_payment_id',  v_pkg_payment_id,
    'payment_recorded',    p_payment_amount > 0
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION record_package_visit IS
  'Atomic "Record Visit" RPC. Wraps session consumption, BOM deduction,
   doctor commission, and optional installment payment (sale + sale_item +
   payment + package_payment) in a single Postgres transaction.
   All validations happen before any writes. Any failure = full rollback.
   remaining_balance is NEVER manually updated — it is a generated column.';

-- ============================================================
-- End of 012_record_visit_rpc.sql
-- ============================================================
